os: linux
dist: bionic

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

jobs:
  allow_failures:
    - jdk:
      - oraclejdk8
      - openjdk8

  include:
    - name: Build Java project (Oracle JDK 8)
      dist: trusty
      language: java
      addons:
        apt:
          packages:
            - oracle-java8-installer
      jdk: oraclejdk8
      script: ./scripts/build_java.sh

    - name: Build Java project (OpenJDK 8)
      language: java
      jdk: openjdk8
      script: ./scripts/build_java.sh

    - name: Build Java project (Oracle JDK 11)
      language: java
      jdk: oraclejdk11
      script: ./scripts/build_java.sh

    - name: Build Java project (OpenJDK 11)
      language: java
      jdk: openjdk11
      script: ./scripts/build_java.sh

    - name: Build Python project (3.6)
      language: python
      python: "3.6"
      script: ./scripts/build_python.sh

    - name: Build Python project (3.7)
      language: python
      python: "3.7"
      script: ./scripts/build_python.sh

    - name: Build Python project (3.8)
      language: python
      python: "3.8"
      script: ./scripts/build_python.sh
