os: linux
dist: bionic

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

jobs:
  allow_failures:
    - env: FAIL="yes"

  fast_finish: true

  include:
    - name: Build Java project (Oracle JDK 8)
      dist: trusty
      language: java
      addons:
        apt:
          packages:
            - oracle-java8-installer
      jdk: oraclejdk8
      env: FAIL="yes"
      script: ./scripts/build_java.sh

    - name: Build Java project (OpenJDK 8)
      language: java
      jdk: openjdk8
      env: FAIL="yes"
      script: ./scripts/build_java.sh

    - name: Build Java project (Oracle JDK 11)
      language: java
      jdk: oraclejdk11
      script: ./scripts/build_java.sh

    - name: Build Java project (OpenJDK 11)
      language: java
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      jdk: openjdk11
      script: ./scripts/build_java.sh

    - name: Build Python project (3.6)
      language: python
      python: "3.6"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f "/home/travis/build/bissim/FLY-graph/python/coverage.xml"
      script: ./scripts/build_python.sh

    - name: Build Python project (3.7)
      language: python
      python: "3.7"
      script: ./scripts/build_python.sh

    - name: Build Python project (3.8)
      language: python
      python: "3.8"
      script: ./scripts/build_python.sh
