jobs:
  include:
    - language: java
      install: true
      jdk:
        - openjdk8
        - oraclejdk11
        - openjdk11
      script:
        - cd java/
        - mvn -T $(nproc) clean package

    - language: python
      python: 
        - "3.6"
        - "3.7"
        - "3.8"
      script:
        - cd python/
        - python3 -m pip install --upgrade setuptools wheel
        - python3 setup.py sdist bdist_wheel
        - ls -la dist/
        - python3 -m pip install -r fly_graph.egg-info/requires.txt
        - cd ..
        - python3 -m python.test.graph_test
        - python3 -m python.test.graph_io_test
