# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Python Deploy

on:
  release:
    types: [created]

env:
  DIST: ${{ github.workspace }}/python/dist
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHON_VERSION: '3.6'
  TAG: ${{ github.event.release.tag_name }}
  WS: ${{ github.workspace }}

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine

    - name: Run tests
      run: |
        pwd
        cd $WS/python/
        pwd
        python -m pip install -r requirements.txt
        python -m fly.graph.tests
        python -m pip install coverage
        python -m coverage report -i fly/graph/*
        python -m coverage xml -i fly/graph/*
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_FLYGRAPH_TOKEN }}
      run: |
        pwd
        cd $WS/python/
        pwd
        python ./setup.py sdist bdist_wheel
        ls -la
        twine upload $DIST/*

    - name: Rename packages
      run: |
        pwd
        ls -la $DIST/
        if [[ ! -e $DIST/fly-graph-${{ env.TAG }}-py3-none.whl ]]; then
            mv $DIST/*.whl $DIST/fly-graph-${{ env.TAG }}-py3-none.whl
        fi
        if [[ ! -e $DIST/fly-graph-${{ env.TAG }}.tar.gz ]]; then
            mv $DIST/*.tar.gz $DIST/fly-graph-${{ env.TAG }}.tar.gz
        fi
        ls -la $DIST/

    - name: Get latest FLY Graph release
      id: release
      uses: bruceadams/get-release@v1.2.1

    - name: Upload Wheel as Release Asset
      id: upload-wheel-release-asset
      uses: actions/upload-release-asset@latest
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ${{ env.DIST }}/fly-graph-${{ env.TAG }}-py3-none.whl
        asset_name: fly-graph-${{ env.TAG }}-py3-none.whl
        asset_content_type: application/x-pywheel+zip

    - name: Upload tarball as Release Asset
      id: upload-zip-release-asset
      uses: actions/upload-release-asset@latest
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ${{ env.DIST }}/fly-graph-${{ env.TAG }}.tar.gz
        asset_name: fly-graph-${{ env.TAG }}.tar.gz
        asset_content_type: application/gzip
