# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Python Deploy

branding:
  icon: 'package'
  color: 'blue'

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_FLYGRAPH_TOKEN }}
      run: |
        python ./python/setup.py sdist bdist_wheel
        ls -la
        twine upload ./dist/*

    - name: Rename packages
      run: |
        ls -la ./dist/
        mv ./dist/*.whl ./dist/fly-graph-${{ github.event.release.tag_name }}-py3-none.whl
        mv ./dist/*.tar.gz ./dist/fly-graph-${{ github.event.release.tag_name }}.tar.gz
        ls -la ./dist/

    - name: Get latest FLY Graph release
      id: release
      uses: bruceadams/get-release@v1.2.0

    - name: Upload Wheel as Release Asset
      id: upload-wheel-release-asset
      uses: actions/upload-release-asset@latest
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./dist/fly-graph-${{ github.event.release.tag_name }}-py3-none.whl
        asset_name: fly-graph-${{ github.event.release.tag_name }}-py3-none.whl
        asset_content_type: application/x-pywheel+zip

    - name: Upload tarball as Release Asset
      id: upload-zip-release-asset
      uses: actions/upload-release-asset@latest
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./dist/fly-graph-${{ github.event.release.tag_name }}.tar.gz
        asset_name: fly-graph-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip
