# This workflow will create an annotated tag and the associated release when
# a push over VERSION file is performed

name: Release

on:
  push:
    branches:
      - 'master'
    paths:
      - 'VERSION' # create a release when 'VERSION' file gets changed

jobs:
  release:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Extract version from VERSION file
      id: version
      run: |
        echo "VERSION=$(cat $WS/VERSION)" >> $GITHUB_ENV
      env:
        WS: ${{ github.workspace }}

    - name: Create signed annotated tag (${{ env.VERSION }})
      id: tag
      uses: mathieudutour/github-tag-action@v4.6
      with:
        github_token: ${{ secrets.AUTH_TOKEN }}
        tag_prefix: ''
        custom_tag: ${{ env.VERSION }}
        create_annotated_tag: true

    - name: Create Release
      id: release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: FLY graph ${{ env.VERSION }}
        body: |
          FLY graph release
        draft: false
        prerelease: false
