name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      with:
        tag_name: ${{ github.ref }}
        release_name: FLY graph ${{ github.ref }}
        body: |
          FLY graph release
        draft: false
        prerelease: false
